name: Run Cypress Tests on LambdaTest

on:
  push:
    branches: [ main ]  # or your dev branch

jobs:
  sanity-test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Sanity Test on LambdaTest
        id: trigger-test
        run: |
          echo "Triggering sanity tests on LambdaTest"
          response=$(curl --location 'https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute' \
            --header 'accept: application/json' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic aW5kZXJqZWV0czpMVF96djlaNEkzUmpqY2psb0x6SzdlNHRDVE5MVU9OaWtQeG0wWUhTeXEzU3BYTmRiQw==' \
            --data '{
                "test_run_id" : "HYPM-550422-1758641678500817102TON",
                "concurrency" : 1,
            }')
          echo "Response: $response"
          job_id=$(echo $response | jq -r '.job_id')
          echo "Job ID: $job_id"
          echo "::set-output name=job_id::$job_id"

      - name: Check Test Status
        run: |
          echo "Checking test status"
          job_id=${{ steps.trigger-test.outputs.job_id }}
          sleep 240  # Wait before checking the status
          response=$(curl --location "https://api.hyperexecute.cloud/v2.0/job/$job_id" \
            --header "accept: application/json" \
            --header "Authorization: Basic aW5kZXJqZWV0czpMVF96djlaNEkzUmpqY2psb0x6SzdlNHRDVE5MVU9OaWtQeG0wWUhTeXEzU3BYTmRiQw==")
            
          echo "Response: $response"
          status=$(echo $response | jq -r '.data.status')
          echo "Test status: $status"
          if [[ "$status" != "completed" ]]; then
            echo "Tests failed. Exiting with error."
            exit 1
          fi
          echo "Sanity tests passed successfully."
